# Use the official Python image as the base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./write_service /app/

RUN pip install --upgrade pip
RUN apt-get update && apt-get install -y default-libmysqlclient-dev
# Install Flask, Flask-SQLAlchemy, Werkzeug, pymysql
RUN pip install --no-cache-dir Flask==2.1.1 Flask-SQLAlchemy==2.4 SQLAlchemy==1.3.24 Werkzeug==2.0.0 pymysql

# Expose port 5001 to the outside world
EXPOSE 5000

# Set the FLASK_APP environment variable
ENV FLASK_APP=write_service.py

# Run app.py when the container launches
# CMD ["python3", "write_service.py"]
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]